stages:
  - build

.caching_rust: &caching_rust
  cache:
    key: $CI_JOB_NAME
    paths:
      - .cargo
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo

.rust-latest: &rust_latest
  stage: build
  image: rust:latest
  script:
    - cargo build --all-features --verbose
    - cargo test --all-features --verbose

.rust-nightly: &rust_nightly
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --all-features --verbose
    - cargo test --all-features --verbose
  allow_failure: true

rust-code-lint:
  stage: build
  image: rust:latest
  tags:
    - docker
    - linux
  before_script:
    - apt-get update -yq && apt-get install -y protobuf-compiler && protoc --version
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    # we need a build since otherwise protobuf modules will not be available
    - cargo build --all-features --verbose
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings
  allow_failure: true

rust-coverage:
  stage: build
  image: rust:latest
  <<: *caching_rust
  tags:
    - docker
    # cargo-tarpaulin only works on linux with privileges to disable ASLR
    - linux
  before_script:
    - apt-get update -yq && apt-get install -y protobuf-compiler && protoc --version
    - cargo install cargo-tarpaulin
  script:
    - cargo tarpaulin --exclude-files "onion_lib/src/p2p_protocol/messages/*" "onion_bin/*" --all-features --out=Xml --out=Html --output-dir=coverage
  after_script:
    - mv coverage/tarpaulin-report.html coverage/index.html
    - mkdir -p public
    - mv coverage/ public/coverage/
  artifacts:
    paths:
      - public/
    reports:
      cobertura: public/coverage/cobertura.xml
  coverage: '/(\d+\.\d+)% coverage/'

rust-latest-linux:
  before_script:
    - apt-get update -yq && apt-get install -y protobuf-compiler && protoc --version
  <<: *rust_latest
  <<: *caching_rust
  tags:
    - docker
    - linux

rust-latest-darwin:
  <<: *rust_latest
  tags:
    - docker
    - darwin
  allow_failure: true

rust-nightly-linux:
  before_script:
    - apt-get update -yq && apt-get install -y protobuf-compiler && protoc --version
  <<: *rust_nightly
  <<: *caching_rust
  tags:
    - docker
    - linux

rust-nightly-darwin:
  <<: *rust_nightly
  tags:
    - docker
    - darwin
