on: [push, pull_request]

name: Code Coverage

jobs:
  grcov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: llvm-tools-preview

      - name: Install Linux Dependencies
        run: sudo apt-get update -yq && sudo apt-get install -y protobuf-compiler && protoc --version

      - name: Install grcov
        run: cargo install grcov

      - name: Run Tests
        run: RUSTFLAGS='-Zinstrument-coverage --cfg coverage' LLVM_PROFILE_FILE='coverage-%p-%m.profraw' cargo test

      - name: Gather Coverage Data
        run: grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing --ignore 'onion_lib/build.rs' --ignore 'onion_lib/src/p2p_protocol/messages/*' --ignore '*.cargo/*' --ignore 'onion_bin/*' --ignore --ignore 'onion_tests/*' -o coverage/ --excl-line coverage-unreachable & grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing --ignore 'onion_lib/build.rs' --ignore '*.cargo/*' --ignore 'onion_lib/src/p2p_protocol/messages/*' --ignore 'onion_bin/*' --ignore --ignore 'onion_tests/*' -o coverage/lcov.info --excl-line coverage-unreachable

      - name: Coveralls Upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: coverage/lcov.info

  grcov_finalize:
    runs-on: ubuntu-latest
    needs: grcov
    steps:
      - name: Coveralls finalization
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true